# Generated by Django 5.2.3 on 2026-01-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_students_options_alter_students_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table=None,
        ),
    ]
